# Generated by Django 4.1.2 on 2022-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkdl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='filename',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
