# Generated by Django 4.1.2 on 2022-10-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkdl', '0002_link_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='filename',
        ),
    ]
